services:
  nzboxer:
    image: ghcr.io/reimaris/nzboxer:latest
    container_name: nzboxer
    ports:
      - "8000:8000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/app/config
    restart: unless-stopped
